---
type: gui
event_server_address: tcp+sbs://127.0.0.1:23012
address: http://0.0.0.0:23023
views:
  - name: login
    view_path: ./views/login
    conf_path: null
  - name: main
    view_path: ./views/main
    conf_path: null
initial_view: login
users:
  - name: user1
    password:
        hash: 0927f26c1e200037ef44e622d39d5b7c201690c85b9aa86545d6583ecff2b02f
        salt: 7af08c40f25d800fa3d1ab3f8199adbd
    roles:
        - user
    view: main
adapters:
  - module: adapters.state
    name: state
log:
    disable_existing_loggers: false
    formatters:
        default: {}
    handlers:
        console:
            class: logging.StreamHandler
            level: INFO
            stream: ext://sys.stdout
    root:
        handlers:
        - console
        level: INFO
    version: 1
...
